.PHONY: default clean cleanup mrproper opti parallel
#mpic++ -I/home/krabbe/boost_1_59_0 -L/home/krabbe/boost_1_59_0/stage/lib -o test.x lol.cpp -Wl,-Bstatic -lboost_mpi -lboost_serialization -Wl,-Bdynamic -lmpi_cxx -lmpi -lgcc_s

### definitions ###
CC = g++
CFLAGS = -g -pthread -Wall -Werror -Wextra -Wno-error=unused-parameter -pedantic -std=c++11 -static-libgcc -static-libstdc++ -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fstack-check
IFLAGS = -I/home/tronje/boost_prefix/include -L/home/tronje/boost_prefix/lib -L/usr/lib/openmpi
LFLAGS = -Wl,-rpath -Wl,/usr/lib/openmpi -Wl,--enable-new-dtags -Wl,-Bstatic -lboost_mpi -lboost_serialization -Wl,-Bdynamic -lmpi_cxx -lmpi -lgcc_s
OBJS = main.o particle.o simulator.o
EXECUTABLE = Simulation.x

### targets ###
# normal
default: Simulation.x

# debug
debug: CFLAGS += -DDEBUG_BUILD
debug: default

# optimized
opti: CFLAGS = -O3 -pedantic -std=c++11
opti: default

#lazy target without any restrictions
lazy: CFLAGS = -g -std=c++11
lazy: default

## Final executable ##
Simulation.x: ${OBJS}
	${CC} ${IFLAGS} ${CFLAGS} ${OBJS} -o ${EXECUTABLE} ${LFLAGS}

### Object files ###
# TODO: throw all these into one target
# Octree
#Octree.o: Octree/Octree.cpp Octree/Octree.hpp Octree/OctreePoint.hpp
#	${CC} ${CFLAGS} -c $<

# main
main.o: main.cpp
	${CC} ${IFLAGS} ${CFLAGS} -c $< ${LFLAGS}

# particle
particle.o: particle.cpp particle.hpp
	${CC} ${IFLAGS} ${CFLAGS} -c $< ${LFLAGS}

# simulator
simulator.o: simulator.cpp simulator.hpp
	${CC} ${IFLAGS} ${CFLAGS} -c $< ${LFLAGS}


### Cleanup utils ###
clean:
	rm -f *.x

cleanup:
	rm -f *.x *.lis

mrproper:
	rm -f *.o *.x *.lis
